### ISSUE TITLE
price not update according to surcharges

### ISSUE THREAD

**Issue by navdeepdhamu** [hefan/solidus_dynamic_variants#2]
Hi,
I want to change the price according to surcharge when I select a value then price should get updated and price should reflect in final price. Also showing the surcharges right side on presentation(value) in dorpdown list.

**Comment by hefan** [comment]
Hello. 
Do i understand right?
Are you talking about the frontend here?
https://camo.githubusercontent.com/6d000a7ade2036b96645b350954c5c67b6980ef3/68747470733a2f2f686566616e2e6769746875622e696f2f696d616765732f66655f70726f64756374735f322e706e67
you mean that directly on the product detail screen the surcharge should be communicated in the dropdown and the selection should live update the final price following the selection?

(i focused on the functionality in the backend and assumed that each frontend is different).

When we are talking about the same thing i could provide you with some example code to achieve what you want..

**Comment by navdeepdhamu** [comment]
Hi
yes. You understand my point . Please share some example code as you have mentioned above.

**Comment by hefan** [comment]
ok. in the branch "live-update-example" there is a basic example of how to do that with jquery:
https://github.com/hefan/solidus_dynamic_variants/commit/ed4220f423470cb288a6e3e4db9474d0537d7bfa

**Comment by navdeepdhamu** [comment]
Hello,
Thank you very much for your help.

**Comment by xeruf** [comment]
Any reason why this was not merged?

**Comment by hefan** [comment]
i focused on the functionality in the backend and assumed that each frontend is different. So i wanted to do only the minimum effort for frontend.
So if it would be merged, it needs to be maintained also and i am not sure if it even helps, because the solidus demo frontend is pretty outdated and not used in realworld projects. Such a kind of jquery dynamic replacement is never done elsewhere in the base demo frontend, so it seems a little bit odd to me.

i just wanted to show a possibility to help navdeepdhamu.
i hope its ok for you.

**Comment by xeruf** [comment]
Yeah makes sense and is indeed helpful. I am wondering though, you used `Deface` to change the frontend which is not recommended?
When using your plugin, how do I then customize the appearance, as your customizations are also not copied over when running `bundle exec rails g solidus:views:override`?
https://guides.solidus.io/developers/customizations/customizing-storefront.html

**Comment by hefan** [comment]
most of deface is used for the backend, maybe i could change the override method for the frontend, but again: for such a tiny intervention i chose deface. The Frontend normally is heavily altered for a real life shop. 

`bundle exec rails g solidus:views:override` just copies the solidus views. you can remove `data-hook="cart_form"` and just use some codee from 
https://github.com/hefan/solidus_dynamic_variants/blob/master/app/views/spree/products/_dynamic_variant_cart_form.html.erb 
or 
https://github.com/hefan/solidus_dynamic_variants/blob/live-update-example/app/views/spree/products/_dynamic_variant_cart_form.html.erb

which fits best in the "spree/products/show" view part of your shop.
