### ISSUE TITLE
Variants availability not showing

### ISSUE THREAD

**Issue by TheSmokingDev** [hefan/solidus_dynamic_variants#4]
Hey, 
So i’m having an issue with an unavailable variant showing up as available.
For example, if a shirt has the options size ad colour, if i make a size zero stock for that colour, the customer can still order it. The item is also no backorderable.
Thank you

**Comment by hefan** [comment]
The Dynamic Variants are meant to be created after the customer selects it. Its meant to be used for something like prescription from eye glass lenses.

From the documentation:
> Assumes the customized Variant will be created after ordering (or is digital). This Means: If track inventory is on, the newly created variant will have track_inventory = false.

So when you like to use stock they cannot be dynamically anymore and you have to use already created variants by removing the dynamic variants checkbox.
