### ISSUE TITLE
Different Selection element

### ISSUE THREAD

**Issue by xeruf** [hefan/solidus_dynamic_variants#6]
I am rather new to ruby on rails, but successfully managed to replace the select by a slider and show a dynamic price. Unfortunately it seems the selection from the slider is not passed to the backend (in the cart I always get the master variant), so now I am wondering what I need to adjust for that?

**Comment by hefan** [comment]
you need to call variant_populate action instead of the populate action.
also you need the options as parameters.

See this example:
https://github.com/hefan/solidus_dynamic_variants/blob/live-update-example/app/views/spree/products/_dynamic_variant_cart_form.html.erb

**Comment by xeruf** [comment]
Thank you, I was missing the HTML form integration, wasn't aware that was how it worked ;)
