### ISSUE TITLE
Not working on rails 7

### ISSUE THREAD

**Issue by fenixbrassi** [hefan/solidus_dynamic_variants#7]
Hi, I want use this gem but when I tried to install it nothing happen.

My gemfile is:
ruby "3.1.2"
gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem "solidus", "~> 3.3"
gem "solidus_auth_devise", "~> 2.5"
gem "solidus_paypal_commerce_platform", "< 1"
gem 'solidus_product_assembly'
gem 'solidus_dynamic_variants', github: 'hefan/solidus_dynamic_variants', branch: 'master'

<img width="1083" alt="Screenshot 2023-04-04 at 17 28 30" src="https://user-images.githubusercontent.com/705877/229944405-b50e91c0-ab9e-4d01-8d2a-b1333ca3db28.png">

And I configured the product properly as you could see the image:

<img width="1571" alt="Screenshot 2023-04-04 at 17 30 06" src="https://user-images.githubusercontent.com/705877/229944623-17d977bd-ce13-4b13-ae57-06919f3d6b46.png">

Then I decided to override the product/form  view just to see if that works but it returns an error:

undefined local variable or method `dynamic_cart_line_items_path' for #<ActionView::Base:0x00000000140a28>

So I don't understand what is happening since I just installed the gem as in the readme said....

**Comment by hefan** [comment]
For Two weeks i wont be at work, so i cannot help really good. But my first guess from your screenshot is that you use the classic solidus frontend for which you should use v1.0.  No form overriding by hand is needed then..

**Comment by fenixbrassi** [comment]
Sorry My mistake I installed it from scratch and it works fine. But I think the problem was because I installed first the v.1 and then I tried to  install the master branch version.
